# Generated by Django 5.1.3 on 2025-09-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('speed', 'Speed Boost'), ('damage', 'Damage Boost'), ('health', 'Health Boost'), ('experience', 'Experience Boost'), ('coins', 'Coins Boost')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('daily_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('level_completion', 'Level Completion'), ('manual', 'Manual Assignment'), ('daily_reward', 'Daily Reward'), ('purchase', 'Purchase')], max_length=20)),
                ('level_earned', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('boost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.boosttype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='game_app.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBoostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('level_used', models.PositiveIntegerField(blank=True, null=True)),
                ('boost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.boosttype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.player')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
    ]
