# Generated by Django 5.1.3 on 2025-09-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.award')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.level')),
            ],
            options={
                'unique_together': {('level', 'award')},
            },
        ),
        migrations.CreateModel(
            name='PlayerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.playertask2')),
            ],
            options={
                'unique_together': {('player', 'level')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.award')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.playertask2')),
            ],
            options={
                'unique_together': {('player', 'award', 'level')},
            },
        ),
    ]
